---
- name: Install Incus on Ubuntu 24.04 from Zabbly repository
  hosts: all
  become: true
  tasks:
    - name: Remove any existing Incus installation
      apt:
        name: incus
        state: absent
        purge: yes
      ignore_errors: true

    - name: Ensure required packages are installed
      apt:
        name:
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Zabbly repository GPG key
      ansible.builtin.get_url:
        url: https://pkgs.zabbly.com/key.asc
        dest: /etc/apt/keyrings/zabbly.asc
        mode: '0644'

    - name: Add Zabbly Incus stable repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/zabbly-incus-stable.sources
        content: |
          Enabled: yes
          Types: deb
          URIs: https://pkgs.zabbly.com/incus/stable
          Suites: {{ ansible_distribution_release }}
          Components: main
          Architectures: {{ ansible_architecture }}
          Signed-By: /etc/apt/keyrings/zabbly.asc
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Incus and its dependencies
      apt:
        name:
          - incus
          - incus-client
          - incus-agent
          - zfsutils-linux
        state: present
        force_apt_get: yes

    - name: Clean apt cache
      apt:
        autoclean: yes
        autoremove: yes

    - name: Ensure Incus is not initialized
      command: incus admin init --preseed < /dev/null
      when: false  # This task will never run, ensuring no initialization