---
- name: Install Incus on Ubuntu 24.04 from Zabbly stable repository
  hosts: all
  become: true
  tasks:
    - name: Remove any existing Incus installation
      apt:
        name: incus
        state: absent
        purge: yes
      ignore_errors: true

    - name: Ensure required packages are installed
      apt:
        name:
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Zabbly Incus repository GPG key
      ansible.builtin.apt_key:
        url: https://pkgs.zabbly.com/key.asc
        state: present

    - name: Add Zabbly Incus repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://pkgs.zabbly.com/incus/stable ./"
        state: present
        filename: zabbly-incus
        update_cache: yes

    - name: Install Incus
      apt:
        name: incus
        state: present

    - name: Install ZFS tools (optional, recommended for storage backend)
      apt:
        name: zfsutils-linux
        state: present

    - name: Clean apt cache
      apt:
        autoclean: yes
        autoremove: yes

    - name: Ensure Incus is not initialized
      command: incus admin init --preseed < /dev/null
      when: false  # This task will never run, ensuring no initialization