---
- name: Install Incus on Ubuntu 24.04 from Zabbly repository
  hosts: all
  become: true
  tasks:
    - name: Remove any existing Incus installation
      apt:
        name: incus
        state: absent
        purge: yes
      ignore_errors: true

    - name: Ensure required packages are installed
      apt:
        name:
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Download Zabbly repository GPG key
      ansible.builtin.get_url:
        url: https://pkgs.zabbly.com/key.asc
        dest: /usr/share/keyrings/zabbly-incus-keyring.gpg
        mode: '0644'

    - name: Add Zabbly repository securely
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/zabbly-incus-keyring.gpg] https://pkgs.zabbly.com/incus/stable ./"
        state: present
        filename: zabbly-incus
        update_cache: yes

    - name: Install Incus from Zabbly repository
      apt:
        name: incus
        state: present

    - name: Clean apt cache
      apt:
        autoclean: yes
        autoremove: yes

    - name: Ensure Incus is not initialized
      command: incus admin init --preseed < /dev/null
      when: false  # This task will never run, ensuring no initialization