---
- name: Install Incus on Ubuntu 24.04 from Zabbly repository
  hosts: all
  become: true
  vars:
    zabbly_key_url: "https://pkgs.zabbly.com/key.asc"
    zabbly_repo: "deb [arch={{ dpkg_architecture.stdout }}] https://pkgs.zabbly.com/incus/stable ./"
  tasks:
    - name: Remove any existing Incus installation
      apt:
        name: incus
        state: absent
        purge: yes
      ignore_errors: true

    - name: Ensure required packages are installed
      apt:
        name:
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Create apt keyring path
      ansible.builtin.file:
        path: "/etc/apt/keyrings"
        state: directory
        mode: '0755'

    - name: Add Zabbly repository key
      ansible.builtin.get_url:
        url: "{{ zabbly_key_url }}"
        dest: "/etc/apt/keyrings/zabbly.gpg"
        mode: '0644'

    - name: Get DPKG architecture
      ansible.builtin.command:
        cmd: dpkg --print-architecture
      register: dpkg_architecture

    - name: Add Zabbly package source
      ansible.builtin.apt_repository:
        repo: "{{ zabbly_repo }}"
        filename: "zabbly"
        state: present
        update_cache: yes

    - name: Install Incus and ZFS tools
      ansible.builtin.apt:
        name:
          - incus
          - zfsutils-linux
        state: present

    - name: Clean apt cache
      apt:
        autoclean: yes
        autoremove: yes

    - name: Ensure Incus is not initialized
      command: incus admin init --preseed < /dev