---
- name: Install Incus on Ubuntu 24.04 from Zabbly repository
  hosts: all
  become: true
  tasks:
    - name: Remove any existing Incus installation
      apt:
        name: incus
        state: absent
        purge: yes
      ignore_errors: true

    - name: Ensure required packages are installed
      apt:
        name:
          - curl
          - gnupg
          - software-properties-common
          - zfsutils-linux
        state: present
        update_cache: yes

    - name: Add Zabbly repository key
      apt_key:
        url: https://pkgs.zabbly.com/key.asc
        state: present

    - name: Add Zabbly repository
      apt_repository:
        repo: "deb [arch=amd64] https://pkgs.zabbly.com/incus/stable ./"
        state: present
        filename: zabbly-incus

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Incus from Zabbly repository
      apt:
        name: incus
        state: present

    - name: Ensure Incus is not initialized
      command: incus admin init --preseed < /dev/null
      when: false  # This task will never run, ensuring no initialization